### ISSUE TITLE
Pausing at final boss triggers loud sound loop in credits

### ISSUE THREAD

**Issue by The-King-of-Toasters** [elishacloud/Silent-Hill-2-Enhancements#424]
At the final boss, if you pause while she's in the middle of her moth attack, the moth sound will become *very loud* and loop continuously in all further cutscenes, movies, credits and the result screen. Not sure if this is a known bug (haha).

Here's me [triggering the bug](https://www.sgregoratto.me/paste/sh2/triggering-bug.mp4), and [the aftermath](https://www.sgregoratto.me/paste/sh2/feelsgoodman-clap.mp4).

**Comment by Polymega** [comment]
Thanks for making us aware of this. I was able to replicate the bug. My gut says this might be a tricky/annoying one to fix. I'll add it to our to-do list.

Thanks again!

**Comment by Mechahamsters** [comment]
Was a fix for this ever found? Ran into this in my very first play through of the game and it kinda ruined the ending.

**Comment by Polymega** [comment]
Not yet. We're looking into properly fixing the game's infamous sound loop bug at this time. My hope is, if/when we find a fix for that, we will have a better general understanding of how the game handles audio calls and can apply that knowledge to hopefully fix this issue.

But you're right that it's important enough to fix. A Hail Mary fix would be to kill all audio threads upon exit of the final boss room ID, similar to as we've done when loading a Game Result file while in-game.

**Comment by Mechahamsters** [comment]
I saw here was a 1.1 version being tested in the thread mentioned above that seemed to have good results with looping audio, although not necessarily this bug. You think it would be worth a shot on my second play through (got in water on the first)

**Comment by Polymega** [comment]
I'm not sure at this time if the final boss butterfly SFX loop is the same issue as the general sound loop bug the game experiences. My gut says they're probably not related so you'd still experience it.

In the meantime the best thing to do would probably be to try and not pull up your pause menu while the butterfly attack SFX is active/playing.

**Comment by Mechahamsters** [comment]
Yeah, the way that triggers, if you switch weapons it'll happen. I might still give a new playthrough a shot on that beta branch and report my findings if yall are interested.

**Comment by Polymega** [comment]
I tried replicating it again and couldn't provoke it. But to be fair, the last time I tested this was serval months ago and I can't quite remember how to do it. 

But perhaps the current audio loop solution (in the current test build) fixes it? If you would want to try yourself that'd be great.

**Comment by Mechahamsters** [comment]
Where can I find that test build?

**Comment by Polymega** [comment]
You can try this test build: [d3d8_b1.7.1914a.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/6834921/d3d8_b1.7.1914a.zip)

**Comment by Mechahamsters** [comment]
Just ended a playthrough with it, encountered 3 bugs (not the moth one). In two rooms of the flooded hotel basement (the kitchen and the stairwell after the Angela encounter), all of James's textures except for his shadows disapeared until the next room was entered. The last bug is that when I was in the final hallway where mary talks to you before you ascend to the roof. I went into my inventory to swap weapons, and it ended the dialog.

**Comment by Polymega** [comment]
So I take it you couldn't make the final boss butterfly attack SFX loop in this test build? If so, that's good to hear.

> In two rooms of the flooded hotel basement (the kitchen and the stairwell after the Angela encounter), all of James's textures except for his shadows disapeared until the next room was entered.

I've had this bug happen to me as well a single time before; just one time, and never again. Since I could never provoke it again, I could never test solutions to fix it.

> The last bug is that when I was in the final hallway where mary talks to you before you ascend to the roof. I went into my inventory to swap weapons, and it ended the dialog.

The is "correct" behavior (happens in all versions of the game).

**Comment by TheMachineAmbassador** [comment]
Hello again now i'm moved here :) Is there anything that can help me to find issue ? I'm looking for the something related to games monster sound call.

**Comment by Polymega** [comment]
Unfortunately, I don't think there's been anything found related to enemy audio calls. Maybe @Bigmanjapan has notes on this or could find useful addresses/instructions?

**Comment by TheMachineAmbassador** [comment]
I guess ill be alone in this audio problem 😀 I have to find anything related about final bosses horde of butterfly attack that could definetly help me to found audio call or i found the games sound call function address already 
 but of course there is too many references to this function. So maybe i can try NOP references until i found the final boss audio call address. But this procesess will really take time i'm afraid.

**Comment by TheMachineAmbassador** [comment]
https://user-images.githubusercontent.com/77938614/156863676-12c921f5-54d8-4e81-804d-3051d961508f.mp4

Hi, i just wanted to share my daily report. After 4-5 days i finally found the call sound effect function of the final boss.
0x004abf4b = mary's horde attack sound effect call address.
[soundcallofMarry.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8189654/soundcallofMarry.zip) (it's not a fix just posted it for the proof of mary can't call the sound effect function )
I found this address after i found the horde spawn location. Nice thing about this we now know what horde attack's sound id 0x49B2 and it will increase process of fixing cause we know play sound effect function address (0x00515580) as well. After activating the cheat table, the sound loop problem is not will be fixed because the problem is inside the play sound effect function i guess or the game cuts the sound with a function, as it does with the load save game button.

https://user-images.githubusercontent.com/77938614/156865033-9c33ce90-2d02-4911-bf5a-77a94ca5d7f1.mp4

I made a "sound effect call" independent from the final boss and the game was still sound looping. So i think the game uses some kind of sound cut function when called by marry (like it does with the load save game button). Now all i have to do is tracking the memory with a debugger and comparing when marry calls the function and when not.

**Comment by Polymega** [comment]
Great research so far, MachineAmbassador! 

> So i think the game uses some kind of sound cut function when called by marry [...] Now all i have to do is tracking the memory with a debugger and comparing when marry calls the function and when not.

Nice thinking. Hopefully this approach will work. It only makes sense that some sort of sound cut function _has_ to exist, yes? Because this SFX will loop while the moths are active, so we know the game doesn't just play the SFX once and then it simply stops. There has to be an indicator for the game to know when to stop it.

I would have to imagine there's also an address that signifies when her moth attack is active. Maybe something dead simple as 0 = moth attack not active, 1 = moth attack active. If this exists, maybe a way to fix this could be: If `Moth Attack = 0` call the sound cut function for this SFX?

Maybe there's a better way to approach it, but that's an idea that quickly came to my mind.

**Comment by TheMachineAmbassador** [comment]
> I would have to imagine there's also an address that signifies when her moth attack is active. Maybe something dead simple as 0 = moth attack not active, 1 = moth attack active. If this exists, maybe a way to fix this could be: If `Moth Attack = 0` call the sound cut function for this SFX?
> Maybe there's a better way to approach it, but that's an idea that quickly came to my mind.

I believe so, i mean that call sound effect function can't work alone there is should be a cut function or in programming thinking ther should be an end of scope or free the memory with moths. This video will help you understand better.

https://user-images.githubusercontent.com/77938614/156897435-bd8ec4cc-f00f-4fb1-a57c-249cfec6a25f.mp4

Now what i did in here is. I simply cut the sound effect of boss and called my own custom sound function. Sound kept looping when no moths were around but when game called moths it got my custom sound call function and destroyed when moths are gone. This sound call function can't be free it should be connected something in the game and should be destroyed with that connected thing otherwise it will endlessly loop. I don't know is there any problem on the other monsters like this in the game if not maybe i can simply add comparison to the free or destruct function after i found functions. Until this time i found this useful values 0x1F7B028 = timer of moth attack, 0x1F7AF8F = if this value is 0 it does something like this things in the game

![moth_special_attack](https://user-images.githubusercontent.com/77938614/156897966-f5c33be5-4322-46aa-8929-579254259896.png)
if moths are summoned and this value is 1 we can tell they're in game :). these are just the first things after call. Now i will gonna do some reverse engineering to understand when and how game destroys the sound.

**Comment by TheMachineAmbassador** [comment]
man i'm really stupid i wasted my hours with reverse engineering the sound call function. I was already found moths base pointer all i had to is simply looking at the what accesses that pointer. Cut the sound effect functions adress: 0x00514d70. It only gets one id value. I believe this function used by load game sound effect aswell. I will look at that after i solve this issue maybe we can double solve issues :)
 
[cutSoundDemo.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8191938/cutSoundDemo.zip)

This is a sample what i used to create call function. If you want to you can test create and cut sound :) (not works perfectly sometimes you may have to press the button a few times ). I used Enchanced Edition's library to create calls with i used in my previous fix. Usage is simple you can create moth sound call with NUMPAD1 and cut the sound with NUMPAD2. After wake up when i have time will look at what we can do with the addresses.

**Comment by Polymega** [comment]
> I used Enchanced Edition's library to create calls with i used in my previous fix. Usage is simple you can create moth sound call with NUMPAD1 and cut the sound with NUMPAD2.

I have to say, this moth cut sound demo works surprisingly well! 😄

**Comment by TheMachineAmbassador** [comment]
> I have to say, this moth cut sound demo works surprisingly well! 😄

I really enjoyed with that demo too especially the cut button for that sound effect 😂 I even want to make a game with this sound effect and title will be "How to make people crazy with one sound effect" :))) I hate this sound so mych effect. I guess there is only one problematic sound effect in this game and that is the worst one. Can't we change this sound effect with this one https://www.youtube.com/watch?v=uV0UG0cwGGs i can add an option for that.
If we get to the point, i love when my theory becomes true :) .Now i want to share what i found so far...
![address](https://user-images.githubusercontent.com/77938614/156941330-66471add-89c5-4ece-9503-c6226130a41c.gif)

In this gif as you can see the count value stops because when i press esc sound effect value must stop aswell but sound effect literally says "nope i will stay independence in here". There are 2 options to fix this problem.

1- For a temporary fix i can put a simple comparison but this won't be a real fix because when you press ESC it won't pause the sound effect it will actually cut the sound effect and wait until new moth spawn. Then i can continue to reverse engineering function to find where is the problem.We can say this is some kind of temporar path.

2- We can wait until i found the problem but it may take long to found problem. I might be close to found problem and i don't want to cut sound effect, when i press esc or go into inventory, i just want to pause sound effect :). And this is the long path.

**Comment by TheMachineAmbassador** [comment]
I found where the game cuts music aswell (0x004AB6B0). I mean when you press inventory button while moth sound effect started it is cuts the sound effect as well sometimes this thing works :) but problem is as i said it cuts the sound i want to pause sound and i guess there is no fuction like that in the game, i have to look other monsters. Maybe if i find out where the game stores the sound effect i can protect that memory with a variable and when the player exits from the pause menu maybe we can get it to start from that memory point. Then i can modify a bit that function (0x004AB6B0) with my own pause sound effect function. Of course it's a bit theory as well, maybe that won't work and simply i can fix the looping issue.

**Comment by Polymega** [comment]
I tested all versions to see how it handles this SFX, and it does something similar to this:

- If moths have spawned
  - Play SFX
    - If inventory/map is opened
      - Stop SFX
    - Else (if returning to gameplay from inventory/map)
      - Play SFX from beginning
- Else (if moths have despawned)
  - Stop SFX

For all versions, this SFX loops infinitely if the pause menu is pulled up.
For the PC version, this SFX will also loop infinitely if you pull up the Options or Load Screen through the pause menu.

> There are 2 options to fix this problem.

Please do what you feel is best. I just don't want you to become frustrated since trying to pause/resume the SFX will surely make this harder than it already is. I think it would be okay to have the SFX completely start over like it's currently doing; I don't think anyone would mind. Perhaps a bonus could be to also stop/restart the SFX when the pause menu is pulled up, since no other version does that?

If we can find addresses/functions that reliably tell us when the moths have spawned/despawned, could we then use your function to start/end the SFX and that theoretically fix this issue?

But either way, for the life of me, I cannot provoke this bug anymore... I wish I knew of a consistent way to make this bug happen...

> Can't we change this sound effect with this one https://www.youtube.com/watch?v=uV0UG0cwGGs i can add an option for that.

😆 We also had someone suggest [adding a whoopie cushion noise](https://www.youtube.com/watch?v=udVX1lMZxwk) for whenever you stomp on Abstract Daddy's in the Hotel, haha.

**Comment by TheMachineAmbassador** [comment]
> Here's me [triggering the bug](https://www.sgregoratto.me/paste/sh2/triggering-bug.mp4), and [the aftermath](https://www.sgregoratto.me/paste/sh2/feelsgoodman-clap.mp4).

I tried this in my github build but that didn't work but after i downloaded latest build from website well yep it triggers everytime i go into inventory. I don't know why this sound issue occurs in latest build, this games handling sound is too bad already. Simply changing this -> 01F7AF8C (1 byte) to 15 will fix the issue its easier than as you expected isn't it :)). I found the problematic function and where the bug is. My all research is completed i guess. I'll be working on a fix today and then I'd better check this out: [Fixing the game to run on multiple cores and not always use 100% of core #423](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/423)

**Comment by TheMachineAmbassador** [comment]
Ah of course :) sending right now

**Comment by TheMachineAmbassador** [comment]
I made this simple fix for the testing. 
[simpleLoopingFix.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8201633/simpleLoopingFix.zip)
Whatever cut sound effect function the inventory menu used, i used the same thing in the pause menu but it didn't work too well (maybe devs wanted to use this function as i did but they may have encountered the same bugs ) so when i programming i will simply call cut sound effect function when player goes into pause menu and recall play sound call.

**Comment by Polymega** [comment]
@Mechahamsters 
> In two rooms of the flooded hotel basement (the kitchen and the stairwell after the Angela encounter), all of James's textures except for his shadows disapeared until the next room was entered.

We have since discovered the cause of this. If you change the game's resolution while playing this'll happen. [We have a fix for this waiting to be implemented.](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/455)

**Comment by TheMachineAmbassador** [comment]
Sorry this fix was related to this. Not for the multiple core fix.

Hello when you have time can you please test this build, this might fix looping issue...

[SoundLoopingFix.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8343944/SoundLoopingFix.zip)

I've also fixed this chainsaw sound looping as i mentioned before.

https://user-images.githubusercontent.com/77938614/159973408-8d300547-6880-4cd6-b3b0-49eac2426468.mp4

**Comment by Polymega** [comment]
> I've also fixed this chainsaw sound looping as i mentioned before.

Oh wow, I never even knew this could happen. For anyone else who wants to test this: You can consistently provoke this bug by _**moving**_ while you start the chainsaw and keep spamming the weapon swap key.

I quickly tried out your build and couldn't make the chainsaw bug happen. (Nice work!) I can do a more thorough test of your build this weekend to try and break it. Do note that I can't seem to make the final boss moth SFX bug happen anymore, so I'm not sure if I can help test that particular bug...

Should I also test to see if this fixing the multicore (sound loop) issue? Or should I keep the game on a single core?

**Comment by TheMachineAmbassador** [comment]
> Should I also test to see if this fixes the multicore (sound loop) issue? Or should I keep the game on a single core?

You don't need to but if you want to try i can't stop you :) Because this 2 issue was logical problem actually.

![chainsaw_code](https://user-images.githubusercontent.com/77938614/160027362-ee467d7e-7419-474d-81a3-c688ed8b68ad.png)

This is what happens when you release ready attack button. There's a check above so you can't hit the swap key when standing still. When james really release chainsaw that animation becomes 0 and sound stops (it's a bit unoptimized code cause it keeps stopping the sound when you holding chainsaw). But when you move and spam the key it bugs the code and that animation things not becomes zero. So it was easy to fix.

![twice-call](https://user-images.githubusercontent.com/77938614/160035261-1f8b992c-c045-4b35-9e02-f4da31b4eb7d.png)

Solving moth issue was funny to fix actually. Because as you can see it sets that special attack value to zero and then calls call_moth_sound function but funny thing is

![special_attack](https://user-images.githubusercontent.com/77938614/160035451-a8f0522e-dfe7-413f-bcac-41f0efa03c22.png)

it calls that function again whenever it sets the specialAttack value to 0.Simply it calls the play sfx thing twice so there is 2 different sfx playing in memory. So when game destroy sound when moths are gone, it just destroys 1 sound. Solving this issue is simple just NOP that value :) but it was easy to miss, took time to find but the important thing is that the problem is solved 😂.

**Comment by Polymega** [comment]
> You don't need to but if you want to try i can't stop you :) Because this 2 issue was logical problem actually.

Unfortunately the generic multicore/sound loop bug is still present. But that's okay since your fix here isn't really meant for that. 

I switched back to playing on a single core for my tests. Anyway, as I was playing I found an extension of the chainsaw bug:

This same bug happens if you start the chainsaw as you are getting hit by an enemy:

https://user-images.githubusercontent.com/27395260/160251174-e4b27df2-eef3-42c5-9977-624a12c53e78.mp4

^ I tested and can confirm this will happen against Lying Figures, cockroaches, mannequins, and the final Mary/Maria boss fight. It's probably safe to assume this would happen against all enemy types.

--------------------

I also tried testing the final boss moth SFX but, as you know, I could only ever make this bug happen once before so I can't 100% confirm anything here. However, going off your notes above this post, it seems like your solution for this fix is solid. :)

**Comment by Polymega** [comment]
I think the chainsaw bug when getting hit by an enemy might be a side effect for your chainsaw bug fix. 😆 

| Bug | Vanilla | With Fix
| --- | --- | --- |
| Chainsaw loops when moving/weapon swapping | Yes | No
| Chainsaw loops when getting hit by an enemy | No | Yes

**Comment by TheMachineAmbassador** [comment]
Ah i noticed that bug yesterday and fixed it already. I always forgetting something when programming 😂😂

[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8356112/Release.zip)

There is also a bug in both versions, when you start chainsaw and press the pause menu key button it starts looping again :). I will fix that now either.

also i added new thing in this build. When you press pause key it stops moth sound. I used same stop sfx function which used by inventory function and it works pretty well. Only there is a bug in that function, when moths timer ends and if you press pause key it destroys them instantly but fixing that is easy. I can compare 2 values and if moths timer value less than the other i can simply add a bit time to moths :)

**Comment by Polymega** [comment]
Nice work! I'm glad fixing that bug was easy!

> There is also a bug in both versions, when you start chainsaw and press the pause menu key button it starts looping again :). I will fix that now either.

Ah, I see what you're saying. I wonder if you can use the same fix from the moth SFX for this? Hopefully it will be an easy thing to fix.

For what it's worth: The chainsaw SFX isn't really annoying so I think it would be okay to keep this behavior, if the fix proves too troublesome.

> also i added new thing in this build. When you press pause key it stops moth sound.

![CGf](https://user-images.githubusercontent.com/27395260/160257214-b6beae40-932e-4892-ab4c-a15e5d91abfc.gif)
(I agree this SFX gets annoying, so it's nice to not hear it in the pause menu either.)

> Only there is a bug in that function, when moths timer ends and if you press pause key it destroys them instantly but fixing that is easy.

I see what you're saying. I did some testing and here's what I observed:

- The game also stops this sound when you pull up the inventory or map screen but the moth timer stays preserved.
- With your current test build, the moths do not resume from their current position when exiting the pause menu. Instead, they respawn as a cluster each time you exit the pause menu:

### Vanilla
https://user-images.githubusercontent.com/27395260/160257823-8f0086d8-8b92-4918-8ed0-d4f7db32ee79.mp4

### Fix
https://user-images.githubusercontent.com/27395260/160257788-4374e154-fd00-4ba7-b447-843f8ef965d8.mp4

> At the same time i'm working on it but due to covid it slowed me down a bit. (got infected yesterday)

Oh no! I'm sorry to hear this. Yes, be sure to get plenty of rest and drink lots of fluids. I hope the side effects of Covid are mild for you. If you're feeling bad please rest and don't worry about these issues right now.

**Comment by Polymega** [comment]
> I did some cleansing in this build.

I tried your new test build and I'm really impressed with your work, Machine Ambassador! It's fantastic that you fixed the original issue of the moth SFX looping during the end scenes, but I never would have imagined the whole final fight being so much better overall. 😃 

You fixed the original bug, you stopped the noise while in the pause screen, you preserved the moth animation/timer... all these things make the final fight feel more stable and less janky. _And_ you also fixed the jank with the chainsaw! It's all wonderful!! 😊 

> for now i'm feeling better but don't know how much worse it can get.

Even if you're feeling better make sure to not overexert yourself. I think it usually takes about two weeks for full recovery, so take things slow during this time.

**Comment by TheMachineAmbassador** [comment]
Thank you again :) Why this kind of issue happens only on final boss still don't get it.Konami pushed them hurry up i guess.After some cleaning and make this code work for other versions i will PR. All this time i was looking wrong place for this issue. I thought real problem in the stop sfx function but that chainsaw sound looping might be so useless but it shined me to find where should i look :). We might looking wrong place for that bug on the multiple core maybe. I mean i know which thing makes the sound looping but still don't know what makes that value to 0. After i finished this project and a bit rest until my infection ends, i will have more time to focus on multiple core issue. Let's see what we can do about it :)

**Comment by Polymega** [comment]
Love what you do, Machine Ambassador! This feature is checked-in and is good to go. This new feature will be included in the next project update. Closing the ticket out. 😁
