### ISSUE TITLE
About remove kanji area from font000

### ISSUE THREAD

**Issue by toraMeeKay** [elishacloud/Silent-Hill-2-Enhancements#581]
Kanji characters are not displayed when custom fonts are enabled.
Could you please restore the remove kanji area (4400x9600)?

Sorry for my bad English

![1](https://user-images.githubusercontent.com/111874292/186153344-52f0c6ef-a9ff-4b89-91eb-6f21933a4b75.jpg)
![2](https://user-images.githubusercontent.com/111874292/186153352-e1624ac2-e9fd-4447-b389-e6c3f3de1ddb.jpg)
![3](https://user-images.githubusercontent.com/111874292/186153357-b3b3e1eb-5ea3-454c-903f-fa5701273b37.jpg)
![4](https://user-images.githubusercontent.com/111874292/186153363-c7cdd5fc-4fe7-4731-9b27-d5ee3c15d984.jpg)
![5](https://user-images.githubusercontent.com/111874292/186153867-55b65e6d-ca13-4ea7-b3c4-fdd09a951423.png)
![6](https://user-images.githubusercontent.com/111874292/186153878-93e54bae-86e9-45fe-96ee-caf8422f4124.png)

**Comment by Polymega** [comment]
We originally made the HD font sheet smaller by removing most of the kanji characters since Silent Hill 2 PC did not include Japanese `.mes` files. (This was also done to reduce the file size of the HD font sheet. ) We can certainly look into restoring the entire font sheet for use if you have fully restored the Japanese language option. 

@belek666 is the creator of the HD font for SH2 PC, so we would need his help/response. 
Belek: Could you work with me to make this happen?

@toraMeeKay 
I have a few questions about the screenshots you shared:
- Did you create the HD Japanese characters seen in these images?
   - If so, did you do this for all the Japanese characters in the font sheet?
   - If so, may I have a copy of this font sheet?
- The original issue with SH2 PC is that it did not include Japanese `.mes` files. Did you create `*_j.mes` files that are fully functional with SH2 PC?

**Comment by toraMeeKay** [comment]
If so, did you do this for all the Japanese characters in the font sheet?
    If so, may I have a copy of this font sheet?

Yes I edited.
[font0000.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9412907/font0000.zip)

    Did you have to modify sh2pc.exe in any way to restore the Japanese language? Or was this purely done by fixing the *_j.mes files?

there is no need to modify sh2pc.exe to restore the Japanese language.

More than 12 years ago, it was discovered that extract a text file (*j_mes files) from the ETC.MGF file of the PS2 Japanese version and replace it with the files of the PC version, it can be translated into Japanese.
The mes files extraction tool was created about 11 years ago.

https://wikiwiki.jp/nihongoka/%E3%83%9E%E3%83%AB%E3%83%81%E3%83%A9%E3%83%B3%E3%82%B2%E3%83%BC%E3%82%B8/n-z#f5say43r

https://www.youtube.com/watch?v=Y3_Fd4xNV8w

**Comment by Polymega** [comment]
> Yes I edited.

Thank you very much for providing this font sheet. I'm not at my computer at this time, but I will look at it later. 

If you made this font sheet in Photoshop, would you be okay to send me your working file (along with the font you used)?

> it was discovered that extract a text file (*j_mes files) from the ETC.MGF file of the PS2 Japanese version and replace it with the files of the PC version

Oh, excellent! We have wanted to include the fully restored Japanese language into our project for a long time now. I'm happy to hear we can now do this.

Would you be able to ZIP all of the restored SH2 PC `*_j.mes` files for me? If not, I can look into using the extraction tool myself. You sending these files would save me time.

I will reach out to belek666 so we can start using the full font sheet since the Japanese language will now be working again. :) I will keep you updated on this progress.

**Comment by toraMeeKay** [comment]
> I will reach out to belek666 so we can start using the full font sheet since the Japanese language will now be working again. :) I will keep you updated on this progress.

Thank you very much for kind response!!
I sent you an email.

**Comment by IlDucci** [comment]
That means problems. I did a quick, cursory check at the files...

Back when Infrid and I did the tests for the sh2msg tool and I asked you to verify the Japanese character set, we used the PAL version's Japanese texts as the reference to get the character table decoded. But some of those files seem to be different with the ones delivered in this dump, which I presume is from an actual NTSC-J version of the game.

So the error means, that character is not in our table because it apparently did not exist in the PAL version. Meaning: I need to find out any additional characters in this dump and add them. Give me a bit of time to find out the offending characters.

**Comment by IlDucci** [comment]
Update on the situation: only three files have issues: config_pc, m_card_x and option. Seeing issues at config_pc, a file that should not be around the PS2 version (I think), makes me think that those files have been altered in a way that is not compatible with sh2msg tool:

I think the three stopping points happen at places where English text should start, so maybe the bytes that indicate if a text should be in English or Japanese are misadded: at config_pc and option the error is caused when the string "Turn Left" shows up and at the m_card_x, seems like the offending string is "MU" (Memory Unit).

I'll ping @Infrid so he can take a look at those files and have a better look at them, but that's what I think is going on. @toraMeeKay , have you changed the files with that Japanese tool you have mentioned?

**Comment by Polymega** [comment]
Ah, the one file I tested with your tool was m_card_x.

> only three files have issues: config_pc, m_card_x and option. [...] those files have been altered in a way that is not compatible with sh2msg tool:

These .mes files very likely have added, PC-specific strings in them, so that may be why these ones are breaking? Theoretically, all other files _should_ be the same as they're the "normal gameplay" .mes files. So nothing would need to be changed between versions for the other .mes files.

> I asked you to verify the Japanese character set, we used the PAL version's Japanese texts as the reference to get the character table decoded

You probably remember this better than I, but wasn't the issue that the PC version dummied out most/all of the Japanese text strings? And that's why we never included them previous to this discussion?

**Comment by IlDucci** [comment]
> These .mes files very likely ~have added~ do NOT have the added, PC-specific strings in them, so that may be why these ones are breaking? Theoretically, all other files _should_ be the same as they're the "normal gameplay" .mes files. So nothing would need to be changed between versions for the other .mes files.

That should break the PC version, not the tool. On that regard, the tool simply counts the amount of strings and adds a number to the text file in order to avoid mistakes by editors. The error that shows up is a character encoding one, not a number of strings one.

> You probably remember this better than I, but wasn't the issue that the PC version dummied out most/all of the Japanese text strings? And that's why we never included them previous to this discussion?

Sorry, I meant the PS2 PAL version of the game as the source of the Japanese assets I asked you to verify. All PS2 versions include the Japanese .mes files, even if the language itself cannot be selected. But yeah, EE did not add the Japanese language primarily because of the dummied out strings/lack of translation for any changes done for EE/lack of HD font.

**Comment by Polymega** [comment]
> Sorry, I meant the PS2 PAL version of the game as the source of the Japanese assets I asked you to verify. 

Oh wow, this was quite a while ago. I _think_ I remember sending this to someone whose fluent in Japanese and they quickly looked over all the files. So maybe the strings _weren't_ dummied out? (At lease for SH2 PC European files?) And if that's the case, we could use the PAL `.*_j.mes` files since we know they all work?

Now that we have a complete font sheet (thanks to toraMeeKay) all that would be left to do is [clean up the files](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit) and do any file translations for PC-unique strings?

...this is all contingent on whether or not the PAL version of SH2 PC included complete Japanese files (which I honestly can't remember any longer...).

**Comment by IlDucci** [comment]
Yes, you helped me with that. The Japanese language from the PS2 PAL was verified by someone who came to your call (which I'm grateful for). However, the SH2 PC version does have the Japanese language dummied out.
 - PS2 and XBOX have the Japanese assets intact, they just have the language removed from the Options menu.
 - PC's PAL version has dummied Japanese mes files.

So yes, we could just clean up the files with what we got. Here's the XBOX Japanese assets: [messageJAPXBOX.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9418323/messageJAPXBOX.zip)

**Comment by Polymega** [comment]
Awesome. Thanks so much, IlDucci.

@toraMeeKay 
The ZIP file IlDucci provided are the Japanese .mes files taken from the Xbox version of the game. All the files from the Xbox version should be compatible with the [SH2MSGConvert](https://gitlab.com/sh2msgconvert/sh2msgconvert) tool, so there should be no errors like what happened with the PS2 extracted files.

The Xbox version might even be better for us since the PC version is based on the Xbox version. So I'm hoping there's better compatibility out-of-the-box. 

I will be periodically messaging you here for help with translating PC-specific strings that the Japanese .mes files may not already include. I will probably also need your help playtesting all of this once everything is done, to make sure all the text strings are correct and accounted for while playing.

**Comment by Polymega** [comment]
@toraMeeKay 
I sent you an email to become an editor for the Google Document below (@IlDucci: I also made you an editor for this document):
https://docs.google.com/document/d/1ET5iIFOjT9YCjejKk2wqa_YVn8itFnUns7Rp76AhCNs/edit?usp=sharing

In this document, you will find the text strings that we will need translations for. The left column are the English strings (for reference) and the right column is for you to input the Japanese translations. 

- If an English string is **highlighted in yellow:** 
   - We will need a translation.
- If an English string is **highlighted in gray:** 
   - This can be ignored.

Please preserve the `---------------` lines. Along the way, you will find things like `<VARIABLE-##>` and `<COLOR-XXX>`. These will also need to be preserved and placed appropriately in your translation lines. 

There are some elements in the game that were never translated into Japanese, [such as the selections in the Options menu](https://user-images.githubusercontent.com/111874292/186153344-52f0c6ef-a9ff-4b89-91eb-6f21933a4b75.jpg), that we now have the opportunity to translate for Japanese players. 😊

Some of these strings are already translated in Japanese. You can reference the Xbox version of these .mes files (below) to copy + paste already completed strings, if you'd like.

- [m_card_x_msg_j.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9419947/m_card_x_msg_j.txt)
- [option_msg_j.txt](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9419950/option_msg_j.txt)

Thank you for your help!

**Comment by IlDucci** [comment]
I'll use a diff to check what strings can be copied from the XBOX/PS2 version.

In the meantime, there's something puzzling me... It's the limit for the two strings in the Save/Load menu. Can you verify the limit is character-based and not byte-based? Because in that case, the amount of characters available for Japanese could be half or even less.

**Comment by IlDucci** [comment]
Okay, I've pasted all the strings that had none or very little changes in English. Since the tool detects the .mes files as Japanese, make sure the variables include the "-LE" part (I have added them).

**Comment by toraMeeKay** [comment]
@Polymega, Thank you as always for your help.
I appreciate too @IlDucci for creating such a wonderful tool!
Shamefully enough, I didn't know about sh2msg... 

Based on the ideas you provided, as long as my ability can reach, I translated them into Japanese.
[JPtranslated&fixed.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9424585/JPtranslated.fixed.zip)

I also did some test play. I hope it's fine...

**Comment by IlDucci** [comment]
Thank you for helping out! I have seen two things, though:
 - @Polymega , did you do the "Strafe" typo here?
```
---------------
Strage left
---------------
Strage right
---------------
```
- @toraMeeKay , the following strings are missing:
```
---------------
Set software 3D sound quality
---------------
Enable Dolby Digital 5.1 sound
---------------
```
```
---------------
Introduction Collage - Voice Version
---------------
James finds Laura on the wall
---------------
James meets Maria on the waterfront
---------------
Hotel flashback
---------------
Maria and James in the hospital
---------------
Maria behind bars
---------------
Eddie on the floor
---------------
Eddie confronts James
---------------
The videotape of Mary
---------------
Maria - Ending
---------------
Rebirth - Ending
---------------
In Water - Ending
---------------
Leave - Ending
---------------
Born From a Wish - Ending
---------------
DOG - Ending
---------------
```
I suppose the two first strings are an issue of unseen texts on EE (Polymega should confirm that), but are the rest of them left in English because a Japanese reader can read those or simply because you do not have a saved game with all the movies unlocked? Because those can be seen, I can assure you. You can find a 100% unlocked save game [here](https://igotaletter.com/temp/sh2pc/TranslationGuide/SH2PC_Translation-Guide_Save-Files.zip).

**Comment by Polymega** [comment]
I'm working on this as we speak! Give me a moment. :)

**Comment by Polymega** [comment]
Thank you both!

@toraMeeKay 
Please see this document again:
https://docs.google.com/document/d/1ET5iIFOjT9YCjejKk2wqa_YVn8itFnUns7Rp76AhCNs/edit#

**config_msg_j.mes**
We need translations for all of these text strings, please.

**Lines that are highlighted bright blue:**
We will need translations for this, please.

**Lines that are highlighted bright green:**
This technically do not need to be translated, but they could be to further assist Japanese players. Would you like to translate these lines?

**Lines that are highlighted in red:**
Important notes to review.

---------------------

@IlDucci 

> but are the rest of them left in English because a Japanese reader can read those or simply because you do not have a saved game with all the movies unlocked?

It might be good for toraMeeKay to translate these lines (highlighted in green and blue in the document). A lot of these lines are still in English for the Japanese PS2/Xbox releases, but if we have the capability to translate them to make things easier for Japanese players, then would should do it.

> Since the tool detects the .mes files as Japanese, make sure the variables include the "-LE" part (I have added them).

I pasted in toraMeeKay's work so far into that document. I might have accidentally overwrote your "-LE" changes. Please verify.

**Comment by Polymega** [comment]
I sent you an email invite to edit this document, toraMeeKay. If it's easier for you, you can edit directly in this document if you'd like then copy it over to a .txt file. IlDucci and I can look over the .txt file to ensure it's formatted correctly for use with the SH2MSGconvert tool.

**Comment by IlDucci** [comment]
> * **Lines that are highlighted bright green:**
>   
>   * These strings technically does not need to be translated, as they are English in the other versions, but they could be translated to further assist Japanese players. Would you like to translate these lines?


I have not said that much regarding many English strings in Japanese because I know that many simple or menu type texts are, indeed left in English as-is (or slightly reworded into what we might call Engrish) in Japanese games/game translations.

**Comment by IlDucci** [comment]
I have not imported the EE-exclusive files into the game (these tests were done with just the XBOX mes files) but I can confirm that @toraMeeKay 's HD font does work with some tweaks, as converted in [here](https://github.com/belek666/fontsh234/issues/8):
![imagen](https://user-images.githubusercontent.com/5641681/186705846-29bf4b16-101b-428c-a139-ee8986100697.png)
![imagen](https://user-images.githubusercontent.com/5641681/186706048-d605a6aa-4d12-498a-8248-030e6dceb6a0.png)
![imagen](https://user-images.githubusercontent.com/5641681/186706385-5eedd19a-4494-4d91-b145-aa70469a10da.png)

**Comment by Polymega** [comment]
By the way: This new font sheet is a work-in-progress. I will very likely need to pixel-shift some characters around. I will also make the "..." look better.

![image](https://user-images.githubusercontent.com/27395260/186710883-804c2a3b-13a3-47b5-b4c3-b474dc24782f.png)

**Comment by toraMeeKay** [comment]
@Polymega, @IlDucci, @belek666
I'm totally moved! and I'm eternally grateful for everyone.


 >the following strings are

Sorry, I hadn't checked thoroughly... and I added japanese translation that you pointed out text.
also I fixed font a little.
[JPtranslated2.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9427245/JPtranslated2.zip)
*Even in the Japanese version, I have not changed the points written in English and the points that have not been confirmed.

and I would like to check two points. 

 >[VERIFY IF WORD “ALTERNATE” IS NEEDED.]

The original Japanese text of the CS version is written as it is, but should I add "ALTERNATE" ?
*In Japanese notation, "ALTERNATE" becomes "(裏)"

 >[translation must be 27 characters or less][MISSING TRANSLATION]

This points is displayed without any problem, but is there any problem?
![save](https://user-images.githubusercontent.com/111874292/186737329-c08c306f-c2f6-46e2-9cf0-714b381637df.png)

**Comment by IlDucci** [comment]
> > [VERIFY IF WORD “ALTERNATE” IS NEEDED.]
> 
> The original Japanese text of the CS version is written as it is, but should I add "ALTERNATE" ? *In Japanese notation, "ALTERNATE" becomes "(裏)"

The Enhanced Edition altered those location names to include the reference that James is in the alternate dimension. I just checked with the original files and it is an addition by @Polymega , so this is a discussion that I should leave to him.

> This points is displayed without any problem, but is there any problem?

There is a bug in the PC version which causes visual glitches whenever entering this screen during gameplay, not from the main menu, and for now it is only solved by reducing the amount of characters used. You have more information in the [Language Translation Guide for EE](https://docs.google.com/document/d/1X4k_2LFjS82ZTm1cbDRtUMB2x1qdfRjNIL0qUgPY7pg/edit), if you want to take a read on the changes and differences.

**Comment by IlDucci** [comment]
More comments on your texts:

```<VARIABLE-01-LE>ボタンで削除できます```
This string does not have a variable for the PC version, just the Backspace key. Can you please update this string removing the variable and adding the key name in Japanese?

**Comment by Polymega** [comment]
> The original Japanese text of the CS version is written as it is, but should I add "ALTERNATE" ?
*In Japanese notation, "ALTERNATE" becomes "(裏)"
>> The Enhanced Edition altered those location names to include the reference that James is in the alternate dimension. I just checked with the original files and it is an addition by @Polymega , so this is a discussion that I should leave to him.

As you know, the Silent Hill games have an alternate (or "Otherworld"). Please use whatever Japanese notation you think is best to describe this. 😊 

> This points is displayed without any problem, but is there any problem?

We will test this later and let you know!

> Oh! And you have not given us a translation file for config_pc. Are you sure you want to leave everything there in English?

Yes, please consider translating this file as well! You can find this file at the top of this document link. If you'd like, [you can edit this document directly](https://docs.google.com/document/d/1ET5iIFOjT9YCjejKk2wqa_YVn8itFnUns7Rp76AhCNs/edit#heading=h.mmr3omjpvagl) (I sent you an invitation email to edit the document).

If you are okay in doing so, it might be easier to make your changes [in this document first](https://docs.google.com/document/d/1ET5iIFOjT9YCjejKk2wqa_YVn8itFnUns7Rp76AhCNs/). That way, we can collaborate in real-time.

**Comment by Polymega** [comment]
> also I fixed font a little.
> [JPtranslated2.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9427245/JPtranslated2.zip)

May I ask you to email me the native PSD with the updates?

**Comment by matheusvb3** [comment]
Hello, I have been stalking the discussions going on in the project's Github (I absolutely adore seeing the work you guys do) and I thought I could point something out that is pertinent to this issue. Very rarely do Japanese video games feature everything written in Japanese because of what can be described as cultural reasons. [This website](https://legendsoflocalization.com/common-problems-when-translating-games-into-japanese/) has a great section discussing this. Even games made by Western studios that get localized to Japanese do not fully translate everything, [this video](https://youtu.be/dcaXPaHvKu0?t=1988) has great examples of that in GTA San Andreas where they kept various strings in English but reworded them with more common words that Japanese people are very likely to understand. This is the reason the Japanese version of SH2 has a lot of strings in English rather than having it 100% in Japanese, thus I believe it would be a good idea to think more about this and consider whether things like the settings screen and video selection menu _really_ need everything in Japanese.

**Comment by Polymega** [comment]
> Very rarely do Japanese video games feature everything written in Japanese because of what can be described as cultural reasons. [This website](https://legendsoflocalization.com/common-problems-when-translating-games-into-japanese/) has a great section discussing this.

Ah, fantastic. This is good to know, and thanks for the tips/useful links, Matheus! (Also, from quickly looking over the site, I will be reading more from Legends of Localization... quite interesting articles!) So knowing this, we're pretty close to having this finished for SH2 PC. toraMeeKay and IlDucci kept most everything that was already in English preserved in English.

There are three lines still in the `m_card_msg_j.mes` file (unique to the PC version) that may benefit from a translation though:
- Delete file with Backspace
- Press Return to continue
- SILENT HILL 2 Save Files

But that leaves the question: Should `config_pc_msg_j.mes` be translated at all or left fully in English? This is a file unique to the PC version.

**Comment by toraMeeKay** [comment]
I'm sorry for the full of mistake... I fixed the points you pointed out.
[JPtranslated3.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9433746/JPtranslated3.zip)

I think people have different tastes, but in certain scenes it was difficult to see the subtitles, so I tried creating a simple outline font version as well
![1](https://user-images.githubusercontent.com/111874292/186920740-f0f257f2-8a20-47a2-9f2b-c40ec2f9301e.png)
.

**Comment by toraMeeKay** [comment]
@Polymega
> May I ask you to email me the native PSD with the updates?

For some reason, I can't attach the file to the email due to an error 😭, so I will send it from this github.
https://mega.nz/file/oxETRZSJ#AjL80mH4PA7Ds04Ed4FK0s24J3XPdkPKy-bqjbKcs3k

**Comment by Polymega** [comment]
Thank you very much!

For the `config_pc_msg_j.mes` there are three strings that go past a 4:3 aspect ratio:

![image](https://user-images.githubusercontent.com/27395260/186936029-1ccf7fd0-0056-4d7e-ab16-df8a00b75e06.png)

Can these be shortened? Or do you think it is better for Japanese players to keep this menu in English? I would like to know your thoughts. Thanks.

-----------------

> I think people have different tastes, but in certain scenes it was difficult to see the subtitles, so I tried creating a simple outline font version as well.

Hmm... this might be happening because of the brightness level being turned up in the options menu? Thankfully, I think this is the only spot in the game where subtitles appear over a relatively bright/white surface like that.

![Screenshot 2022-08-26 11-10-14](https://user-images.githubusercontent.com/27395260/186936416-be16728b-c9d4-44ce-bc0c-f7736223166c.png)

**Comment by matheusvb3** [comment]
@Polymega I'm just as clueless as you are, but thankfully toraMeeKay will be able to provide some insight. I'm glad to be able to help!

**Comment by toraMeeKay** [comment]
>Can these be shortened? Or do you think it is better for Japanese players to keep this menu in English? I would like to know your thoughts.

It's a complicated issue... Certainly, I feel that there is no problem even if write it back to English notation..
The alternative when translating into Japanese is
___________________________
アクション／調べる:

↓

決定／調べる:
___________________________
ライト Ｏｎ／Ｏｆｆ:

↓

点灯／消灯:
___________________________
回復アイテムを使用:

↓

治療する
___________________________

Even if write it like this, it means almost the same thing.
[option_msg_j.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9437106/option_msg_j.zip)


 > I think this is the only spot in the game where subtitles appear over a relatively bright/white surface like that.

Oh... Exactly, when I set the brightness to 3 or less, it was fine as you said.
I am terribly sorry for the lack of confirmation.

**Comment by IlDucci** [comment]
> > I think this is the only spot in the game where subtitles appear over a relatively bright/white surface like that.
> 
> Oh... Exactly, when I set the brightness to 3 or less, it was fine as you said. I am terribly sorry for the lack of confirmation.

Do not worry at all! These things happen.

I think we are almost done with the additional translation changes for the base game. This is what is left to do right now:
 - @Polymega 's polishing of the Japanese font texture. (we should note that such a large texture is going to cause issues for players using integrated graphics cards, such as Intel's).
 - The d3d8.res's strings also need translation. While I assume many of the strings will stay in English, I would like to be sure of this. On the other hand (this is more for Polymega), have we ever checked out the encoding supported for this file in Japanese? I'm seeing ASCII for the EFIGS characters, what's Japanese going to read? S-JIS? The custom encoding?

```\hPAUSED
\hResume
\hSave Game
\hLoad Game
\hOptions
\hQuit
\hExit to Main Menu?
\hYes
\hNo
\c\hPlease insert Silent Hill 2 disc
\c\hPaused
\c\hWrong disc
\c\hController not connected
\c\hDisc not inserted
\c\hDisc tray open
\c\hNow loading
\c\hPlease wait
\c\hChecking disc
\c\hExit to main menu?
\c\hYes
\c\hNo
Button %d
\hGAME SAVED
\hCAN'T SAVE
\hNO QUICK SAVE
\hConfigure in d3d8.ini file
\hConfigure in Windows Sound Settings```

 - When the font is done, testing of the Japanese version should be the next point of business.
 - And after that, if you still want to translate materials for the Enhanced Edition, you should see the [Launcher](https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Launcher/config.xml) and the [Installer](https://github.com/nipkownix/SH2EE-web-installer/tree/master/languages).

**Comment by Polymega** [comment]
> The alternative when translating into Japanese is

Wonderful! These changes now fit in a 4:3 aspect ratio. 😊 Thank you.

I am speaking with Belek to see if we can change the file format used for the font sheet to reduce its size. Once we have the format finalized, I will send you all the files back (including the native PSD file).

--------------

@IlDucci 
> On the other hand (this is more for Polymega), have we ever checked out the encoding supported for this file in Japanese? I'm seeing ASCII for the EFIGS characters, what's Japanese going to read? S-JIS? The custom encoding?

These strings are stored directly in the main game binary. Belek made it possible for us to modify them through an external file. iirc, he said the file must stay in ANSI format. This might be a Belek question to ask...

-----------
@toraMeeKay  
> if you still want to translate materials for the Enhanced Edition, you should see the Launcher and the Installer.

Yes! Our project also includes an [installer](https://youtu.be/LylafxQta9w?t=65) and [launcher](https://youtu.be/LylafxQta9w?t=192).

I know this is a lot to ask, but if you would be interested in translating the text for these tools into Japanese, I'm sure other Japanese speakers would be very appreciative. There is quite a lot to translate, so I understand if you would you prefer not to do this. If you would like to do this, here are the files that need translating:

- **Installer**
   - https://github.com/nipkownix/SH2EE-web-installer/blob/master/languages/English.iss
   - https://github.com/nipkownix/SH2EE-web-installer/blob/master/languages/English-license.rtf
- **Launcher**
   - https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Launcher/config.xml

**Comment by Polymega** [comment]
Yep, I already have this changed/ready to go. 👍 
Thanks!

**Comment by Polymega** [comment]
@toraMeeKay 
Me we also ask you to translate the following line?

```
Files are missing. Please re-install Silent Hill 2.
```

**Comment by toraMeeKay** [comment]
>Do not worry at all! These things happen.

Thank you for your kind words.<3 @IlDucci



@Polymega

Below is a message in Japanese. 

___________________________
Files are missing. Please re-install Silent Hill 2.
↓
ファイルが見つかりません。 Silent Hill 2を再インストールして下さい。
___________________________

I tried to translate the Installer into Japanese as much as possible, but Please discard if you don't need it.

[installer_J.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9453679/installer_J.zip)

For your information, If I were to translate Launcher into Japanese, It may take a lot of time.💦

**Comment by IlDucci** [comment]
Thank you very much for your hard work, toraMeeKay!

@Polymega , do not add the strings for d3d8.res as-is. I have tested both getting them in UTF-8 (that was definitely not going to work) and also in Shift-JIS (in a hacky way) and the strings show incorrectly. Belek is definitely needed for this, since the d3d8.res files are stuck in ASCII format and that does not support anything other than Western Europe languages.

**Comment by Polymega** [comment]
​@toraMeeKay
> I tried to translate the Installer into Japanese as much as possible, but Please discard if you don't need it.

This is excellent! Thank you so much!! We all really appreciate your hard work. I believe I have all of the Japanese `.mes` files updated and account for now. 

Please download the updated Japanese `.mes` files for your own records (and to test, if you'd like):
[SH2 PC Japanese Message Files.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9456830/SH2.PC.Japanese.Message.Files.zip)

And here is the TGA, DDS, and PSD file for the font sheet. Please download and update these files for your records, as well:
http://www.igotaletter.com/temp/sh2pc/SH2PC_HD_Font.zip

> For your information, If I were to translate Launcher into Japanese, It may take a lot of time.💦

No worries! There is no rush for a translation. If you would also like to translate this document then please take your time! Also, we understand if you would prefer not to translate such a large document. Please do not feel obligated to do so. We're very thankful for all the help you've provided so far. 😊

@IlDucci
>  Belek is definitely needed for this, since the d3d8.res files are stuck in ASCII format and that does not support anything other than Western Europe languages.

Would you mind making Belek aware of this over in his repository? You are much more knowledgeable with encoding nuances than I am.

**Comment by IlDucci** [comment]
> Would you mind making Belek aware of this over in his repository? You are much more knowledgeable with encoding nuances than I am.

No need! Today I tinkered some more with the d3d8.res file and I was able to make it show Japanese characters. Long story short, that "\h" added at the beginning of each string is a flag that tells the game to read the strings in one-byte/Western mode (like what happens with the .mes files). By removing that flag and encoding each Japanese string into S-JIS, you get a jackpot... except for the "Button %s" string, which should use Windows encoding. The problem is, which one? Because while I do remember that Windows started with S-JIS and then jumped on Unicode, I'd need to be sure before encoding that string. For now I've left it in English.

![sh2pc 2022-08-31 11-57-40-99](https://user-images.githubusercontent.com/5641681/187653885-83184ed5-f39e-425a-86bc-2319bd570ba1.png)
![sh2pc 2022-08-31 11-57-52-26](https://user-images.githubusercontent.com/5641681/187653891-476a61fa-c95a-4d44-8269-031e7767ff2e.png)
![sh2pc 2022-08-31 11-57-54-92](https://user-images.githubusercontent.com/5641681/187653894-dbd3fd8e-a022-40c7-a814-f8cbb9c3c772.png)

Here is the altered d3d8.res file: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9460543/d3d8.zip)

@toraMeeKay , would you please be able to rewrite the Windows再生デバイスを設定します string so it has one less character?

**Comment by toraMeeKay** [comment]
@Polymega
That's awesome! I played a little test and the fonts and text were perfect.
However, the "KB" part of "空き容量：VARIABLE-01-LE ＫＢ (en: Free space: VARIABLE-01  KB)" in line 333 of the m_card_x_msg_j.txt file may be unnecessary...
![Freespace](https://user-images.githubusercontent.com/111874292/187689077-922c1036-fa79-4618-a705-9657eecb6934.jpg)

I'm sorry if I'm not correct.

 >No worries! There is no rush for a translation. If you would also like to translate this document then please take your time! 

Thank you :)  If you would like, I will slowly work on the Japanese translation.


@IlDucci
Wow! Thank you as always for your great ideas <3

  >would you please be able to rewrite the Windows再生デバイスを設定します string so it has one less character?

Hmmm... It was bit of a difficult decision, but I think "サウンド設定を調整します" would work fine too.

**Comment by Polymega** [comment]
> No need! Today I tinkered some more with the d3d8.res file and I was able to make it show Japanese characters.

@IlDucci Nice!! Great job! 👍  Here's my one and only suggestion: The Japanese language on other SH2 versions says "PAUSE" when bringing up the pause menu. Should the main PAUSE header stay in English?

> However, the "KB" part of "空き容量：VARIABLE-01-LE ＫＢ (en: Free space: VARIABLE-01 KB)" in line 333 of the m_card_x_msg_j.txt file may be unnecessary...

@toraMeeKay Oh, sorry, I forgot to mention that part: I have made Elisha (our lead programmer) aware of this bug and it will be fixed in the future. [This relates to our storage size fix.](https://enhanced.townofsilenthill.com/SH2/config.htm#ImproveStorageSupport) Thanks for testing our changes and catching that! 😊 

> Hmmm... It was bit of a difficult decision, but I think "サウンド設定を調整します" would work fine too.

@toraMeeKay Unfortunately, this may not be ideal. Without getting too technical, you can no longer adjust this sound setting through the game. From Windows Vista moving forward, Windows prevents applications (such as this game) from changing sound settings for your PC. It now must be done through Windows Sound Settings. Ideally, the description will tell the user that they now must change this setting through Windows Sound Settings. 

@IlDucci A last effort might be to use non-full width characters here for "Windows"? I know it's not ideal, but the string would probably fit then...

**Comment by toraMeeKay** [comment]
@Polymega
 >This relates to our storage size fix.

I understand. I’m so sorry to bother you many times :_(

 >Ideally, the description will tell the user that they now must change this setting through Windows Sound Settings.

Sorry for the misunderstanding.
In that case, the ideal would be "Windows側で再生デバイスを調整して下さい" but that is too long description, so I think "現在のWindows再生デバイス" is fine.

**Comment by IlDucci** [comment]
> @IlDucci A last effort might be to use non-full width characters here for "Windows"? I know it's not ideal, but the string would probably fit then...

It's not me. The texts in English are being written in ASCII/variable width mode, it's the game that is choosing to represent in S-JIS mode those characters as fullwidths.

**Comment by toraMeeKay** [comment]
@Polymega
I have corrected a few Japanese descriptions in the d3d8.res file. Hopefully there will be no problems.🥺
[d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9481785/d3d8.zip)

@nipkownix
Certainly. I have translated it into Japanese. In case you're wondering, the (400), (404), (502), and (503) errors are not edited because they are written in English even in Japan.

Best regards,
[default.iss.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/9481787/default.iss.zip)

**Comment by Polymega** [comment]
> I have corrected a few Japanese descriptions in the d3d8.res file.

This is wonderful! Thank you! I would like to include your name in the credits of our project. Would you like to be credited as toraMeeKay or another name?

**Comment by toraMeeKay** [comment]
>I would like to include your name in the credits of our project. Would you like to be credited as toraMeeKay or another name?

Oh! Honestly, I'm sorry to ask you to add my name in the credits since I don't do anything much... but if you could add my name to the credits, please use "toraMeeKay".

**Comment by Polymega** [comment]
> I'm sorry to ask you to add my name in the credits since I don't do anything much..

You're being too kind! 😅 Your help is incredibly important to us! Without your help, we would still not have the Japanese characters in an editable PSD file. And without this file, we would not be able to offer an HD font sheet for the language.

Also, your translation help for our installer and launcher will be a big help for other Japanese players!

> but if you could add my name to the credits, please use "toraMeeKay".

No problem! Please look forward to seeing your name on the project website and SH2 PC credits video the next time we release an update. 😊 

Oh, another question:
For SH2 and SH3, their main menus are written in English for the Japanese language. The same is true for SH3 PC's pause menu:

![image](https://user-images.githubusercontent.com/27395260/188279703-23453fda-7c17-4332-a6d3-2fead4990984.png)

Should we make the following words English for the Japanese language in the `d3d8.res` file?

![image](https://user-images.githubusercontent.com/27395260/188279746-facee533-ccd6-4ffb-af65-cfb2b9b4a01e.png)

**Comment by toraMeeKay** [comment]
>Should we make the following words English for the Japanese language in the d3d8.res file?

I was worried about that point too...
English if it's to be the same as SH3 PC, Japanese translation if it's to match the recent console & PC games... I truly am sorry, I'll leave the final decision to Polymega.🥺

**Comment by matheusvb3** [comment]
Hi @toraMeeKay Sorry to bother you but I wanted to ask you something. In the coin riddle in the apartments there was a change in the translation from Japanese to English that left me curious. I found out about it from [this video](https://www.youtube.com/watch?v=gUG8DssjShw). In Japanese the "old man" is referred to in the poem as "the one with gray or white hair," which is a clever trick because the word they used (_kami_) can also be used to describe gods. They reinforce this later in the same verse by making a biblical reference to "the son of man." They purposefully made it so that the reader has to realize that the poem is not talking about a "white bright god" but rather "the one with white hair," that is, the old man. The problem is that the HD version of the man in the coin used in this mod is bald, while the original does have hair... a little at least (and also a chin goatee apparently?)

![image](https://user-images.githubusercontent.com/98937378/190287034-87474c88-c81d-41a8-b9d6-08344695e28f.png)

Do you think this can confuse Japanese speakers?

If you did not know, in the English version all religious context and references to being disgraced (falling from grace) were completely removed. This is a shame because, as the narrator in the video explains, the coin puzzle could have been a reference to Judas from the Bible, who betrayed Jesus for thirty pieces of silver and fell from grace.

This is just me rambling, but I also find it interesting how the Japanese version refers to the prisoner as "prisoner of war," because now it makes sense why she is blindfolded, it could be because she is a slave (captive/prisoner of war)... though the poem also refers to her as a "felon" so it is implied she also committed an atrocious crime, which is not present in the English version. I think this could be a reference to Angela's story.

It's very fascinating how we ended up getting a very simplified version of this poem.

**Comment by toraMeeKay** [comment]
Ohh... I had no idea.
In SH3, in response to Douglas's "Revenge doesn't solve anything" quote, Heather replied, "Maybe not, but that's what I'm going to do." in the English version, but in the Japanese version, she replied, "It might at least give me a sense of self-satisfaction." I didn't know anything other than that there was bit of a discussion in Japan that the impression would change considerably depending on the difference in this translation.

For sure, there is no hair on the coin of the old man in Full HD mod, but since it was difficult to tell whether he originally had hair or not, Japanese had no choice but to guess that "white hair" refers to the "old man," and I think that there is no particular problem.

I am sorry that my English is so bad.
Thanks for the interesting discussion, @matheusvb3!

**Comment by matheusvb3** [comment]
Thank you a lot for your insight @toraMeeKay!!! I was not sure if the connection between the old man coin and the way he is described in the poem would be easy to understand for the Japanese. I have the impression that the poem is a little harder overall to interpret in the Japanese version, but it is also more interesting and artistic in my opinion. Also I didn't know about that change in SH3, I agree it changes Heather's personality and reasoning too much, sadly...

**Comment by Polymega** [comment]
I could see that shape on his chin being a goatee, but this man has no discernible hair on his head in the original image. If he has hair, it would have to be something like a buzz cut (a nearly shaved head). But as the texture stands, there's no defining features to show hair on his head.

**Comment by matheusvb3** [comment]
> I could see that shape on his chin being a goatee, but this man has no discernible hair on his head in the original image. If he has hair, it would have to be something like a buzz cut (a nearly shaved head). But as the texture stands, there's no defining features to show hair on his head.

I had always interpreted that darker shading as some sort of weird old-fashioned monk-ish buzzcut (thanks for reminding me of this word, it was at the tip of my tongue), but now that I think of it it could just be that the stock photo they used to make the coin (assuming they used one) had the man receiving light directly from his front (our right), leaving the back of his head with more shadows. That would explain why he has that black splodge on the back of his neck. Sorry for the confusion. 😓

**Comment by Polymega** [comment]
@toraMeeKay 
Sorry, we forgot two lines that need to be translated. Can the following be translated? 

```
Cycle Target Left:
Cycle Target Right:
```

^ I'm not sure if those Japanese translations will be too long so, just in case, may I also ask you to translate the following?

```
Target Enemy Left:
Target Enemy Right:
Aim Left:
Aim Right:
```

Thank you!

**Comment by Polymega** [comment]
Hi again @toraMeeKay,

Would you be able to help us translate those few, short strings above this post? We missed these before and, after they are translated, I believe everything will be complete/accounted for the Japanese language pack.

Thank you!
